[[providers]]
name = "tegola"
type = "mvt_postgis"
host = "${DATABASE_HOST_URI}"
port = 5432
database = "${DATABASE_NAME}"
user = "${DATABASE_USERNAME}"
password = "${DATABASE_PASSWORD}"
srid = 4326

[[providers.layers]]
name = "table_name"
geometry_fieldname = "geometry"
geometry_type = "MultiPolygon"
sql = "SELECT ST_AsMVTGeom(geometry, !BBOX!) AS geometry, \"Postcode\", \"Output Area\", \"LSOA\", \"MSOA\", \"Gas Supply\" FROM leo_master.off_gas_postcodes WHERE geometry && !BBOX!"


[[maps]]
name = "tegola"
center = [ 7.0982, 50.7374, 11.0,]
[[maps.layers]]
provider_layer = "tegola.table_name"

[webserver]
port = ":8080"
